# Generated by Django 4.2.30 on 2026-05-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_collection'),
        ('site_settings', '0003_backuphistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero_slides/')),
                ('subtitle', models.CharField(blank=True, default='', max_length=200)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('title_emphasized', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('cta1_text', models.CharField(blank=True, default='Shop Now', max_length=100)),
                ('cta1_link', models.CharField(blank=True, default='/products', max_length=200)),
                ('cta2_text', models.CharField(blank=True, default='View Lookbook', max_length=100)),
                ('cta2_link', models.CharField(blank=True, default='/collections', max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'hero_slides',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_type', models.CharField(choices=[('carousel', 'Cinematic Carousel'), ('trending_grid', 'Trending Product Grid'), ('split_screen', 'Split Screen Collection'), ('minimal_video', 'Minimal Video Showcase')], default='carousel', max_length=20)),
                ('primary_heading', models.CharField(blank=True, default='ELEVATE YOUR LIVING SPACE', max_length=200)),
                ('secondary_heading', models.CharField(blank=True, default='Discover our new collection', max_length=200)),
                ('description', models.TextField(blank=True, default='Experience the epitome of luxury with our hand-crafted, sustainably sourced furniture.')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='hero_featured/')),
                ('background_video_url', models.URLField(blank=True, default='')),
                ('cta_text', models.CharField(blank=True, default='Shop Now', max_length=100)),
                ('cta_link', models.CharField(blank=True, default='/products', max_length=200)),
                ('featured_products', models.ManyToManyField(blank=True, related_name='featured_in_hero', to='products.product')),
            ],
            options={
                'verbose_name': 'Hero Settings',
                'verbose_name_plural': 'Hero Settings',
                'db_table': 'hero_settings',
            },
        ),
    ]
