# Generated by Django 4.2.30 on 2026-05-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_heroslide_herosettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Dravo Homes', max_length=200)),
                ('tagline', models.CharField(blank=True, default='', max_length=300)),
                ('about_text', models.TextField(blank=True, default='')),
                ('mission', models.TextField(blank=True, default='')),
                ('vision', models.TextField(blank=True, default='')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.TextField(blank=True, default='')),
                ('instagram', models.URLField(blank=True, default='')),
                ('facebook', models.URLField(blank=True, default='')),
                ('linkedin', models.URLField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profile',
                'db_table': 'company_profile',
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('file', models.FileField(upload_to='media_library/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_type', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'db_table': 'media_assets',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
