# Generated by Django 4.2.30 on 2026-05-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cataloguepage',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='catalogues/pdfs/'),
        ),
    ]
