# Generated by Django 4.2.30 on 2026-05-09 20:30

import catalogues.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0002_alter_cataloguepage_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=catalogues.models.catalogue_pdf_path),
        ),
        migrations.DeleteModel(
            name='CataloguePage',
        ),
    ]
